/**
 * GENERATED by `scripts/gen-session-format-catalog.ts` — do not edit by hand.
 * The direct imports keep the installed writer readable without mounted plugins.
 */

import { KNOWN_SESSION_EVENT_TYPES } from '@orochi-network/oh-session'
import { createSessionFormatCatalog } from '@orochi-network/oh-session-format'
import type { SessionFormatCatalogOptions } from '@orochi-network/oh-session-format'
import { validateInstalledCurrentSessionArtifact, validateInstalledCurrentSessionHeader } from './current.ts'
import { sessionFormatV5Codec } from './current-format/codec.ts'
import { assertV5Header, restoreV5Artifact } from './current-format/validation-v5.ts'

/** Static assembly of the one installed writer, shared by every current read. */
export const sessionFormatCatalogOptions: SessionFormatCatalogOptions = {
  currentVersion: 5,
  codec: sessionFormatV5Codec,
  currentEncoder: sessionFormatV5Codec,
  restoreCurrent(artifact) {
    const restored = restoreV5Artifact(artifact, KNOWN_SESSION_EVENT_TYPES)
    validateInstalledCurrentSessionArtifact(restored)
    return restored
  },
  restoreCurrentHeader(header) {
    assertV5Header(header)
    validateInstalledCurrentSessionHeader(header)
    return header
  },
}

/** Physical dispatch and current-format restore, independent of mounted plugins. */
export const sessionFormatCatalog = createSessionFormatCatalog(sessionFormatCatalogOptions)
