/** Generate the build-static Session format catalog from the writer constant and current codec. */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const root = resolve(import.meta.dirname, '..')
const OUT = 'packages/session/session-format-catalog/src/generated.ts'

/**
 * Read the current writer version from the core Session source of truth.
 * @param scanRoot - repository root whose Session source is authoritative.
 * @returns the current non-negative Session format version.
 */
export function readCurrentSessionFormatVersion(scanRoot: string = root): number {
  const source = readFileSync(resolve(scanRoot, 'packages/core/session/src/types.ts'), 'utf8')
  const match = source.match(/export const SESSION_FORMAT_VERSION = (\d+)\b/)
  if (match === null) throw new Error('gen-session-format-catalog: cannot read SESSION_FORMAT_VERSION')
  return safeVersion(Number(match[1]), 'SESSION_FORMAT_VERSION')
}

function safeVersion(value: unknown, label: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0 || Object.is(value, -0)) {
    throw new Error(`gen-session-format-catalog: ${label} must be a non-negative safe integer`)
  }
  return value as number
}

/**
 * Render the deterministic single-generation catalog source.
 *
 * This build ships no migration chain, so the catalog declares exactly one codec
 * and no migrations; the generator keeps the writer constant, the current-format
 * module, and the generated file in agreement.
 *
 * @param currentVersion - writer version the catalog must declare.
 * @returns complete generated TypeScript source.
 */
export function renderSessionFormatCatalog(currentVersion: number): string {
  return [
    '/**',
    ' * GENERATED by `scripts/gen-session-format-catalog.ts` — do not edit by hand.',
    ' * The direct imports keep the installed writer readable without mounted plugins.',
    ' */',
    '',
    "import { KNOWN_SESSION_EVENT_TYPES } from '@orochi-network/oh-session'",
    "import { createSessionFormatCatalog } from '@orochi-network/oh-session-format'",
    "import type { SessionFormatCatalogOptions } from '@orochi-network/oh-session-format'",
    "import { validateInstalledCurrentSessionArtifact, validateInstalledCurrentSessionHeader } from './current.ts'",
    "import { sessionFormatV5Codec } from './current-format/codec.ts'",
    "import { assertV5Header, restoreV5Artifact } from './current-format/validation-v5.ts'",
    '',
    '/** Static assembly of the one installed writer, shared by every current read. */',
    'export const sessionFormatCatalogOptions: SessionFormatCatalogOptions = {',
    `  currentVersion: ${currentVersion},`,
    '  codec: sessionFormatV5Codec,',
    '  currentEncoder: sessionFormatV5Codec,',
    '  restoreCurrent(artifact) {',
    '    const restored = restoreV5Artifact(artifact, KNOWN_SESSION_EVENT_TYPES)',
    '    validateInstalledCurrentSessionArtifact(restored)',
    '    return restored',
    '  },',
    '  restoreCurrentHeader(header) {',
    '    assertV5Header(header)',
    '    validateInstalledCurrentSessionHeader(header)',
    '    return header',
    '  },',
    '}',
    '',
    '/** Physical dispatch and current-format restore, independent of mounted plugins. */',
    'export const sessionFormatCatalog = createSessionFormatCatalog(sessionFormatCatalogOptions)',
    '',
  ].join('\n')
}

function main(): void {
  const currentVersion = readCurrentSessionFormatVersion(root)
  const output = renderSessionFormatCatalog(currentVersion)
  const target = resolve(root, OUT)
  if (process.argv.includes('--check')) {
    let current = ''
    try { current = readFileSync(target, 'utf8') } catch { /* missing is stale */ }
    if (current !== output) {
      console.error(`gen-session-format-catalog: ${OUT} is stale; run pnpm run gen-session-format-catalog`)
      process.exitCode = 1
      return
    }
    console.log(`gen-session-format-catalog: ${OUT} is up to date.`)
    return
  }
  writeFileSync(target, output)
  console.log(`gen-session-format-catalog: wrote ${OUT}.`)
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main()
